version: '3'

networks:
    webapp:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
        networks:
            - webapp

    php:
        build:
            context: .
            dockerfile: dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
        networks:
            - webapp
